import { FC } from "react";
import { BsInfoCircle } from "react-icons/bs";

import Panel from "./Panel";

const DescriptionPanel: FC = () => {
  return (
    <Panel
      initiallyDeployed
      title={
        <>
          <BsInfoCircle className="text-muted" /> Description
        </>
      }
    >
      <p>
        This playground renders the exact <code>graph.json</code> generated by <code>export.py</code>. Each node is a
        wrestler in a chosen weight class, sized by the total number of recorded matches and colored by their win
        percentage. Directed edges point from winners to the corresponding opponents.
      </p>
      <p>
        To refresh the data, run <code>python export.py</code> with any date or weight filters you need, then copy the
        resulting <code>graph.json</code> into <code>sigma.js/packages/demo/public/graph.json</code> (or symlink it). The
        dev server automatically reloads the file on refresh.
      </p>
      <p>
        Hover a node to highlight its direct matchups. Click a node or select it from the search box to zoom the camera
        and inspect detailed win/loss counts in the "Wrestler details" panel. The UI is powered by React, Vite, and
        <a target="_blank" rel="noreferrer" href="https://www.sigmajs.org">
          sigma.js
        </a>
        .
      </p>
    </Panel>
  );
};

export default DescriptionPanel;
